import React from 'react'
import {
  Users,
  Home,
  Hammer,
  Bug,
  TreePine,
  Key,
  Wrench,
  Building,
  Sparkles,
  Laptop,
  Globe,
  Scale,
  Car,
  Calendar,
  GraduationCap,
  Languages,
  Music,
  Palette,
  Dumbbell,
  Heart,
  Sparkle,
  CircleDot,
  Briefcase,
  Camera,
  Phone,
  Shield,
  Star,
  Truck,
  Scissors,
  Book,
  Coffee,
  Utensils,
} from 'lucide-react'

const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  users: Users,
  home: Home,
  hammer: Hammer,
  bug: Bug,
  trees: TreePine,
  key: Key,
  wrench: Wrench,
  building: Building,
  sparkles: Sparkles,
  laptop: Laptop,
  globe: Globe,
  scale: Scale,
  car: Car,
  calendar: Calendar,
  'graduation-cap': GraduationCap,
  languages: Languages,
  music: Music,
  palette: Palette,
  dumbbell: Dumbbell,
  heart: Heart,
  sparkle: Sparkle,
  circle: CircleDot,
  briefcase: Briefcase,
  camera: Camera,
  phone: Phone,
  shield: Shield,
  star: Star,
  truck: Truck,
  scissors: Scissors,
  book: Book,
  coffee: Coffee,
  utensils: Utensils,
}

export function renderCategoryIcon(iconName: string, className?: string): React.ReactNode {
  const IconComponent = ICON_MAP[iconName] || ICON_MAP['circle']
  return <IconComponent className={className || 'w-7 h-7'} />
}

export const AVAILABLE_ICONS = Object.entries(ICON_MAP).map(([name, component]) => ({
  name,
  component,
}))
